version: '2'
catalog:
  name: "ADC"
  version: "1.0.0"
  description: |
    (Experimental) Artery Developer Community
  minimum_rancher_version: "1.0.0"
  maximum_rancher_version: "5.0.0"
  maintainer: "liuzhenzhen <liuzhenzhen@thunisoft.com>"
  uuid: adc-0
adc:
  scale: 1
  start_on_create: true
  labels:
    io.rancher.container.requested_ip: "10.42.200.202"
    k8s-app: service
mysql:
  scale: 1
  start_on_create: true
  labels:
    io.rancher.container.requested_ip: "10.42.200.203"
    k8s-app: service-db