apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
  - productpage
  http:
  - route:
    - destination:
        host: productpage
        subset: {{ .Values.productpage.version | quote }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: reviews
        subset: v2
  - route:
    - destination:
        host: reviews
        {{- if .Values.reviews.version }}
        subset: {{ .Values.reviews.version | quote }}
        {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - route:
    - destination:
        host: ratings
        {{- if .Values.ratings.version }}
        subset: {{ .Values.ratings.version | quote }}
        {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
  - details
  http:
  - route:
  {{- range $key, $value := .Values.details -}}
  {{- if ne ($value.weight | toString) "0" }}
    - destination:
        host: details
        subset: {{ $value.version }}
      weight: {{ $value.weight }}
  {{- end }}
  {{- end -}}
